name: build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Docker build & publish
      uses: docker/build-push-action@v1
      with:
        username: "${{ secrets.DOCKER_REGISTRY_USERNAME }}"
        password: "${{ secrets.DOCKER_REGISTRY_PASSWORD }}"
        build-args:
          - GITHUB_USER=Mengli619
          - GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}"
        registry: registry.cn-beijing.aliyuncs.com
        repository: myrenderer/server
        tags: latest
